### ISSUE TITLE
Authentication on any domain

### ISSUE THREAD

**Issue by axellorreyne** [KNowledgeOnWebScale/solid-authentication-browser-extension#1]
As of now, the extension will only replace unauthenticated request by authenticated requests on requests done on the [SolidLab Playground](https://pod.playground.solidlab.be/)

This should be extended to any instance of the Community Solid Server on any domain, including localhost.

**Comment by pheyvaer** [comment]
Do you mean request with a WebID that is running on a pod on the playground? Or do you mean request to a resource on a pod on the playground? Or both?
