### ISSUE TITLE
Catch 401 unauthorized instead of forcing headers on every request

### ISSUE THREAD

**Issue by axellorreyne** [KNowledgeOnWebScale/solid-authentication-browser-extension#10]
Instead of pushing headers containing authentication parameters on every request, the extension should catch unauthorized request (returning a 401 status code) and refetch on this url containing the correct headers.

**Comment by pheyvaer** [comment]
When I try to access an resource for which I have to be logged in I get a 401, not a 403. Can you give an example where you get a 403?
