### ISSUE TITLE
SyntaxError on import

### ISSUE THREAD

**Issue by axellorreyne** [KNowledgeOnWebScale/solid-authentication-browser-extension#3]
In some cases, web-ext return the following error upon running `npm start`
```
SyntaxError: import declarations may only appear at top level of a module
```
I expect this to happen because `getToken()` is imported and called directly in: https://github.com/KNowledgeOnWebScale/solid-authentication-browser-extension/blob/9552a8529e966b3208a0d112f5f98005cb54989a/popup/popup.js#L16-L19

Instead, it should be a background process that is called as a [runtime message](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage)

**Comment by pheyvaer** [comment]
"In some cases". Does that mean that in some cases it doesn't? What cases are that?

**Comment by axellorreyne** [comment]
I didn't have these errors while developing on another machine using a firefox development build (and running it from the manifest.json file) but I did get them using the built-in web-ext browser that deploys on running web-ext verbose with npm.

I fixed this by calling the script, returning the import error, as a module in e5127b7f075be28452e22459343f249bdf377e10
